title: Aymane Amine Bsc # your name (or website title) here
logo: "/images/index.png?raw=true" # your photo (or logo) here
description: > # 
  Master student at the university of Vienna    <br>
  Specialization: Stochastics and dynamical systems
  <br><br>
  Interests: Optimal transport, Geometry, Stochastic analysis and Machine learning
  <a href="https://www.linkedin.com/in/aymane-amine-8b5b03148/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
